"""Building spawning — utility functions for placing buildings in the world."""

from __future__ import annotations

from canopy import world, Vec3, Quat
from canopy.components import Transform, Mesh, BuildingData, Zone

# Predefined building asset paths. These resolve to .canasset files
# generated by canopy-pipeline.
RESIDENTIAL_ASSETS = {
    1: "assets/buildings/residential/low_01.canasset",
    2: "assets/buildings/residential/mid_01.canasset",
    3: "assets/buildings/residential/high_01.canasset",
}

COMMERCIAL_ASSETS = {
    1: "assets/buildings/commercial/small_shop_01.canasset",
    2: "assets/buildings/commercial/mid_retail_01.canasset",
    3: "assets/buildings/commercial/mall_01.canasset",
}

INDUSTRIAL_ASSETS = {
    1: "assets/buildings/industrial/warehouse_01.canasset",
    2: "assets/buildings/industrial/factory_01.canasset",
    3: "assets/buildings/industrial/heavy_01.canasset",
}


def spawn_residential_block(
    position: Vec3,
    zone_id: int,
    tier: int = 2,
    rotation_y: float = 0.0,
) -> int:
    """Spawn a residential building entity at the given position.

    Args:
        position:   World-space position of the building origin.
        zone_id:    Economic zone this building belongs to.
        tier:       Density tier (1=low, 2=mid, 3=high) — affects asset + capacity.
        rotation_y: Y-axis rotation in radians.

    Returns:
        Entity ID (integer) of the spawned building.

    Note:
        Capacity values are approximate — the economic simulation adjusts them
        dynamically based on upgrade events and disaster damage.
    """
    tier = max(1, min(3, tier))
    asset_path = RESIDENTIAL_ASSETS[tier]
    capacity = {1: 12, 2: 48, 3: 120}[tier]

    entity = world.spawn()

    world.add(entity, Transform(
        position=position,
        rotation=Quat.from_euler_xyz(0.0, rotation_y, 0.0),
        scale=Vec3.one(),
    ))

    world.add(entity, Mesh(
        asset=asset_path,
        lod_bias=0.0,
        cast_shadow=True,
        receive_shadow=True,
    ))

    world.add(entity, BuildingData(
        zone_id=zone_id,
        capacity=capacity,
        occupancy=0,
        construction_progress=0.0,  # Will be animated by construction system
        health=1.0,
    ))

    world.add(entity, Zone(
        zone_type="residential",
        zone_id=zone_id,
        tier=tier,
        damage=0.0,
    ))

    return entity.id


def spawn_commercial_block(
    position: Vec3,
    zone_id: int,
    tier: int = 1,
) -> int:
    """Spawn a commercial building."""
    tier = max(1, min(3, tier))
    asset_path = COMMERCIAL_ASSETS[tier]
    jobs = {1: 8, 2: 30, 3: 200}[tier]

    entity = world.spawn()
    world.add(entity, Transform(position=position))
    world.add(entity, Mesh(asset=asset_path))
    world.add(entity, BuildingData(zone_id=zone_id, capacity=jobs))
    world.add(entity, Zone(zone_type="commercial", zone_id=zone_id, tier=tier))
    return entity.id


def spawn_industrial_block(
    position: Vec3,
    zone_id: int,
    tier: int = 1,
) -> int:
    """Spawn an industrial building."""
    tier = max(1, min(3, tier))
    asset_path = INDUSTRIAL_ASSETS[tier]
    jobs = {1: 20, 2: 80, 3: 400}[tier]

    entity = world.spawn()
    world.add(entity, Transform(position=position))
    world.add(entity, Mesh(asset=asset_path))
    world.add(entity, BuildingData(zone_id=zone_id, capacity=jobs))
    world.add(entity, Zone(zone_type="industrial", zone_id=zone_id, tier=tier))
    return entity.id


def demolish_building(entity_id: int) -> None:
    """Despawn a building entity.

    In a real implementation this would:
    1. Play a demolition animation (particle system, sound)
    2. Refund partial construction cost
    3. Notify the economic system to recompute zone demand
    4. Remove from zone map

    For now it's an immediate despawn.
    """
    # We need a proper Entity handle — entity IDs are opaque in Python
    # Phase 2: world.get_entity(id) → Entity
    print(f"demolish_building({entity_id}) — not yet implemented (Phase 2)")
